;;; Code generated by schema-generator.lisp: DO NOT EDIT.

(in-package :openapi-parser/schema/3/interface)

(defmethod ->openapi ((instance openapi-parser/schema/3.0.1:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::openapi)
      (slot-value instance 'openapi-parser/schema/3.0.1::openapi)
      default))

(defmethod ->info ((instance openapi-parser/schema/3.0.1:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::info)
      (slot-value instance 'openapi-parser/schema/3.0.1::info)
      default))

(defmethod ->servers ((instance openapi-parser/schema/3.0.1:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::servers)
      (slot-value instance 'openapi-parser/schema/3.0.1::servers)
      default))

(defmethod ->paths ((instance openapi-parser/schema/3.0.1:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::paths)
      (slot-value instance 'openapi-parser/schema/3.0.1::paths)
      default))

(defmethod ->components ((instance openapi-parser/schema/3.0.1:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::components)
      (slot-value instance 'openapi-parser/schema/3.0.1::components)
      default))

(defmethod ->security ((instance openapi-parser/schema/3.0.1:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::security)
      (slot-value instance 'openapi-parser/schema/3.0.1::security)
      default))

(defmethod ->tags ((instance openapi-parser/schema/3.0.1:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::tags)
      (slot-value instance 'openapi-parser/schema/3.0.1::tags)
      default))

(defmethod ->external-docs ((instance openapi-parser/schema/3.0.1:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::external-docs)
      (slot-value instance 'openapi-parser/schema/3.0.1::external-docs)
      default))

(defmethod ->title ((instance openapi-parser/schema/3.0.1:<info>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::title)
      (slot-value instance 'openapi-parser/schema/3.0.1::title)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.0.1:<info>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::description)
      (slot-value instance 'openapi-parser/schema/3.0.1::description)
      default))

(defmethod ->terms-of-service ((instance openapi-parser/schema/3.0.1:<info>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::terms-of-service)
      (slot-value instance 'openapi-parser/schema/3.0.1::terms-of-service)
      default))

(defmethod ->contact ((instance openapi-parser/schema/3.0.1:<info>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::contact)
      (slot-value instance 'openapi-parser/schema/3.0.1::contact)
      default))

(defmethod ->license ((instance openapi-parser/schema/3.0.1:<info>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::license)
      (slot-value instance 'openapi-parser/schema/3.0.1::license)
      default))

(defmethod ->version ((instance openapi-parser/schema/3.0.1:<info>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::version)
      (slot-value instance 'openapi-parser/schema/3.0.1::version)
      default))

(defmethod ->name ((instance openapi-parser/schema/3.0.1:<contact>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::name)
      (slot-value instance 'openapi-parser/schema/3.0.1::name)
      default))

(defmethod ->url ((instance openapi-parser/schema/3.0.1:<contact>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::url)
      (slot-value instance 'openapi-parser/schema/3.0.1::url)
      default))

(defmethod ->email ((instance openapi-parser/schema/3.0.1:<contact>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::email)
      (slot-value instance 'openapi-parser/schema/3.0.1::email)
      default))

(defmethod ->name ((instance openapi-parser/schema/3.0.1:<license>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::name)
      (slot-value instance 'openapi-parser/schema/3.0.1::name)
      default))

(defmethod ->url ((instance openapi-parser/schema/3.0.1:<license>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::url)
      (slot-value instance 'openapi-parser/schema/3.0.1::url)
      default))

(defmethod ->url ((instance openapi-parser/schema/3.0.1:<server>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::url)
      (slot-value instance 'openapi-parser/schema/3.0.1::url)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.0.1:<server>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::description)
      (slot-value instance 'openapi-parser/schema/3.0.1::description)
      default))

(defmethod ->variables ((instance openapi-parser/schema/3.0.1:<server>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::variables)
      (slot-value instance 'openapi-parser/schema/3.0.1::variables)
      default))

(defmethod ->enum ((instance openapi-parser/schema/3.0.1:<server-variable>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::enum)
      (slot-value instance 'openapi-parser/schema/3.0.1::enum)
      default))

(defmethod ->default ((instance openapi-parser/schema/3.0.1:<server-variable>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::default)
      (slot-value instance 'openapi-parser/schema/3.0.1::default)
      default))

(defmethod ->description
           ((instance openapi-parser/schema/3.0.1:<server-variable>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::description)
      (slot-value instance 'openapi-parser/schema/3.0.1::description)
      default))

(defmethod ->schemas ((instance openapi-parser/schema/3.0.1:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::schemas)
      (slot-value instance 'openapi-parser/schema/3.0.1::schemas)
      default))

(defmethod ->responses ((instance openapi-parser/schema/3.0.1:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::responses)
      (slot-value instance 'openapi-parser/schema/3.0.1::responses)
      default))

(defmethod ->parameters ((instance openapi-parser/schema/3.0.1:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::parameters)
      (slot-value instance 'openapi-parser/schema/3.0.1::parameters)
      default))

(defmethod ->examples ((instance openapi-parser/schema/3.0.1:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::examples)
      (slot-value instance 'openapi-parser/schema/3.0.1::examples)
      default))

(defmethod ->request-bodies ((instance openapi-parser/schema/3.0.1:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::request-bodies)
      (slot-value instance 'openapi-parser/schema/3.0.1::request-bodies)
      default))

(defmethod ->headers ((instance openapi-parser/schema/3.0.1:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::headers)
      (slot-value instance 'openapi-parser/schema/3.0.1::headers)
      default))

(defmethod ->security-schemes
           ((instance openapi-parser/schema/3.0.1:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::security-schemes)
      (slot-value instance 'openapi-parser/schema/3.0.1::security-schemes)
      default))

(defmethod ->links ((instance openapi-parser/schema/3.0.1:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::links)
      (slot-value instance 'openapi-parser/schema/3.0.1::links)
      default))

(defmethod ->callbacks ((instance openapi-parser/schema/3.0.1:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::callbacks)
      (slot-value instance 'openapi-parser/schema/3.0.1::callbacks)
      default))

(defmethod ->field* ((instance openapi-parser/schema/3.0.1:<paths>) &optional default)
  (if (slot-boundp instance 'field*)
      (slot-value instance 'field*)
      default))

(defmethod ->$ref ((instance openapi-parser/schema/3.0.1:<path-item>) &optional default)
  (if (slot-boundp instance '$ref)
      (slot-value instance '$ref)
      default))

(defmethod ->summary ((instance openapi-parser/schema/3.0.1:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::summary)
      (slot-value instance 'openapi-parser/schema/3.0.1::summary)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.0.1:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::description)
      (slot-value instance 'openapi-parser/schema/3.0.1::description)
      default))

(defmethod ->get ((instance openapi-parser/schema/3.0.1:<path-item>) &optional default)
  (if (slot-boundp instance 'get)
      (slot-value instance 'get)
      default))

(defmethod ->put ((instance openapi-parser/schema/3.0.1:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::put)
      (slot-value instance 'openapi-parser/schema/3.0.1::put)
      default))

(defmethod ->post ((instance openapi-parser/schema/3.0.1:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::post)
      (slot-value instance 'openapi-parser/schema/3.0.1::post)
      default))

(defmethod ->delete ((instance openapi-parser/schema/3.0.1:<path-item>) &optional default)
  (if (slot-boundp instance 'delete)
      (slot-value instance 'delete)
      default))

(defmethod ->options ((instance openapi-parser/schema/3.0.1:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::options)
      (slot-value instance 'openapi-parser/schema/3.0.1::options)
      default))

(defmethod ->head ((instance openapi-parser/schema/3.0.1:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::head)
      (slot-value instance 'openapi-parser/schema/3.0.1::head)
      default))

(defmethod ->patch ((instance openapi-parser/schema/3.0.1:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::patch)
      (slot-value instance 'openapi-parser/schema/3.0.1::patch)
      default))

(defmethod ->trace ((instance openapi-parser/schema/3.0.1:<path-item>) &optional default)
  (if (slot-boundp instance 'trace)
      (slot-value instance 'trace)
      default))

(defmethod ->servers ((instance openapi-parser/schema/3.0.1:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::servers)
      (slot-value instance 'openapi-parser/schema/3.0.1::servers)
      default))

(defmethod ->parameters ((instance openapi-parser/schema/3.0.1:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::parameters)
      (slot-value instance 'openapi-parser/schema/3.0.1::parameters)
      default))

(defmethod ->tags ((instance openapi-parser/schema/3.0.1:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::tags)
      (slot-value instance 'openapi-parser/schema/3.0.1::tags)
      default))

(defmethod ->summary ((instance openapi-parser/schema/3.0.1:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::summary)
      (slot-value instance 'openapi-parser/schema/3.0.1::summary)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.0.1:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::description)
      (slot-value instance 'openapi-parser/schema/3.0.1::description)
      default))

(defmethod ->external-docs ((instance openapi-parser/schema/3.0.1:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::external-docs)
      (slot-value instance 'openapi-parser/schema/3.0.1::external-docs)
      default))

(defmethod ->operation-id ((instance openapi-parser/schema/3.0.1:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::operation-id)
      (slot-value instance 'openapi-parser/schema/3.0.1::operation-id)
      default))

(defmethod ->parameters ((instance openapi-parser/schema/3.0.1:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::parameters)
      (slot-value instance 'openapi-parser/schema/3.0.1::parameters)
      default))

(defmethod ->request-body ((instance openapi-parser/schema/3.0.1:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::request-body)
      (slot-value instance 'openapi-parser/schema/3.0.1::request-body)
      default))

(defmethod ->responses ((instance openapi-parser/schema/3.0.1:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::responses)
      (slot-value instance 'openapi-parser/schema/3.0.1::responses)
      default))

(defmethod ->callbacks ((instance openapi-parser/schema/3.0.1:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::callbacks)
      (slot-value instance 'openapi-parser/schema/3.0.1::callbacks)
      default))

(defmethod ->deprecated ((instance openapi-parser/schema/3.0.1:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::deprecated)
      (slot-value instance 'openapi-parser/schema/3.0.1::deprecated)
      default))

(defmethod ->security ((instance openapi-parser/schema/3.0.1:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::security)
      (slot-value instance 'openapi-parser/schema/3.0.1::security)
      default))

(defmethod ->servers ((instance openapi-parser/schema/3.0.1:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::servers)
      (slot-value instance 'openapi-parser/schema/3.0.1::servers)
      default))

(defmethod ->description
           ((instance openapi-parser/schema/3.0.1:<external-documentation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::description)
      (slot-value instance 'openapi-parser/schema/3.0.1::description)
      default))

(defmethod ->url
           ((instance openapi-parser/schema/3.0.1:<external-documentation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::url)
      (slot-value instance 'openapi-parser/schema/3.0.1::url)
      default))

(defmethod ->name ((instance openapi-parser/schema/3.0.1:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::name)
      (slot-value instance 'openapi-parser/schema/3.0.1::name)
      default))

(defmethod ->in ((instance openapi-parser/schema/3.0.1:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::in)
      (slot-value instance 'openapi-parser/schema/3.0.1::in)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.0.1:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::description)
      (slot-value instance 'openapi-parser/schema/3.0.1::description)
      default))

(defmethod ->required ((instance openapi-parser/schema/3.0.1:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::required)
      (slot-value instance 'openapi-parser/schema/3.0.1::required)
      default))

(defmethod ->deprecated ((instance openapi-parser/schema/3.0.1:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::deprecated)
      (slot-value instance 'openapi-parser/schema/3.0.1::deprecated)
      default))

(defmethod ->allow-empty-value
           ((instance openapi-parser/schema/3.0.1:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::allow-empty-value)
      (slot-value instance 'openapi-parser/schema/3.0.1::allow-empty-value)
      default))

(defmethod ->style ((instance openapi-parser/schema/3.0.1:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::style)
      (slot-value instance 'openapi-parser/schema/3.0.1::style)
      default))

(defmethod ->explode ((instance openapi-parser/schema/3.0.1:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::explode)
      (slot-value instance 'openapi-parser/schema/3.0.1::explode)
      default))

(defmethod ->allow-reserved ((instance openapi-parser/schema/3.0.1:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::allow-reserved)
      (slot-value instance 'openapi-parser/schema/3.0.1::allow-reserved)
      default))

(defmethod ->schema ((instance openapi-parser/schema/3.0.1:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::schema)
      (slot-value instance 'openapi-parser/schema/3.0.1::schema)
      default))

(defmethod ->example ((instance openapi-parser/schema/3.0.1:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::example)
      (slot-value instance 'openapi-parser/schema/3.0.1::example)
      default))

(defmethod ->examples ((instance openapi-parser/schema/3.0.1:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::examples)
      (slot-value instance 'openapi-parser/schema/3.0.1::examples)
      default))

(defmethod ->content ((instance openapi-parser/schema/3.0.1:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::content)
      (slot-value instance 'openapi-parser/schema/3.0.1::content)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.0.1:<request-body>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::description)
      (slot-value instance 'openapi-parser/schema/3.0.1::description)
      default))

(defmethod ->content ((instance openapi-parser/schema/3.0.1:<request-body>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::content)
      (slot-value instance 'openapi-parser/schema/3.0.1::content)
      default))

(defmethod ->required ((instance openapi-parser/schema/3.0.1:<request-body>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::required)
      (slot-value instance 'openapi-parser/schema/3.0.1::required)
      default))

(defmethod ->schema ((instance openapi-parser/schema/3.0.1:<media-type>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::schema)
      (slot-value instance 'openapi-parser/schema/3.0.1::schema)
      default))

(defmethod ->example ((instance openapi-parser/schema/3.0.1:<media-type>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::example)
      (slot-value instance 'openapi-parser/schema/3.0.1::example)
      default))

(defmethod ->examples ((instance openapi-parser/schema/3.0.1:<media-type>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::examples)
      (slot-value instance 'openapi-parser/schema/3.0.1::examples)
      default))

(defmethod ->encoding ((instance openapi-parser/schema/3.0.1:<media-type>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::encoding)
      (slot-value instance 'openapi-parser/schema/3.0.1::encoding)
      default))

(defmethod ->content-type ((instance openapi-parser/schema/3.0.1:<encoding>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::content-type)
      (slot-value instance 'openapi-parser/schema/3.0.1::content-type)
      default))

(defmethod ->headers ((instance openapi-parser/schema/3.0.1:<encoding>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::headers)
      (slot-value instance 'openapi-parser/schema/3.0.1::headers)
      default))

(defmethod ->style ((instance openapi-parser/schema/3.0.1:<encoding>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::style)
      (slot-value instance 'openapi-parser/schema/3.0.1::style)
      default))

(defmethod ->explode ((instance openapi-parser/schema/3.0.1:<encoding>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::explode)
      (slot-value instance 'openapi-parser/schema/3.0.1::explode)
      default))

(defmethod ->allow-reserved ((instance openapi-parser/schema/3.0.1:<encoding>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::allow-reserved)
      (slot-value instance 'openapi-parser/schema/3.0.1::allow-reserved)
      default))

(defmethod ->field* ((instance openapi-parser/schema/3.0.1:<responses>) &optional default)
  (if (slot-boundp instance 'field*)
      (slot-value instance 'field*)
      default))

(defmethod ->default ((instance openapi-parser/schema/3.0.1:<responses>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::default)
      (slot-value instance 'openapi-parser/schema/3.0.1::default)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.0.1:<response>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::description)
      (slot-value instance 'openapi-parser/schema/3.0.1::description)
      default))

(defmethod ->headers ((instance openapi-parser/schema/3.0.1:<response>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::headers)
      (slot-value instance 'openapi-parser/schema/3.0.1::headers)
      default))

(defmethod ->content ((instance openapi-parser/schema/3.0.1:<response>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::content)
      (slot-value instance 'openapi-parser/schema/3.0.1::content)
      default))

(defmethod ->links ((instance openapi-parser/schema/3.0.1:<response>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::links)
      (slot-value instance 'openapi-parser/schema/3.0.1::links)
      default))

(defmethod ->field* ((instance openapi-parser/schema/3.0.1:<callback>) &optional default)
  (if (slot-boundp instance 'field*)
      (slot-value instance 'field*)
      default))

(defmethod ->summary ((instance openapi-parser/schema/3.0.1:<example>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::summary)
      (slot-value instance 'openapi-parser/schema/3.0.1::summary)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.0.1:<example>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::description)
      (slot-value instance 'openapi-parser/schema/3.0.1::description)
      default))

(defmethod ->value ((instance openapi-parser/schema/3.0.1:<example>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::value)
      (slot-value instance 'openapi-parser/schema/3.0.1::value)
      default))

(defmethod ->external-value ((instance openapi-parser/schema/3.0.1:<example>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::external-value)
      (slot-value instance 'openapi-parser/schema/3.0.1::external-value)
      default))

(defmethod ->operation-ref ((instance openapi-parser/schema/3.0.1:<link>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::operation-ref)
      (slot-value instance 'openapi-parser/schema/3.0.1::operation-ref)
      default))

(defmethod ->operation-id ((instance openapi-parser/schema/3.0.1:<link>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::operation-id)
      (slot-value instance 'openapi-parser/schema/3.0.1::operation-id)
      default))

(defmethod ->parameters ((instance openapi-parser/schema/3.0.1:<link>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::parameters)
      (slot-value instance 'openapi-parser/schema/3.0.1::parameters)
      default))

(defmethod ->request-body ((instance openapi-parser/schema/3.0.1:<link>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::request-body)
      (slot-value instance 'openapi-parser/schema/3.0.1::request-body)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.0.1:<link>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::description)
      (slot-value instance 'openapi-parser/schema/3.0.1::description)
      default))

(defmethod ->server ((instance openapi-parser/schema/3.0.1:<link>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::server)
      (slot-value instance 'openapi-parser/schema/3.0.1::server)
      default))

(defmethod ->name ((instance openapi-parser/schema/3.0.1:<tag>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::name)
      (slot-value instance 'openapi-parser/schema/3.0.1::name)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.0.1:<tag>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::description)
      (slot-value instance 'openapi-parser/schema/3.0.1::description)
      default))

(defmethod ->external-docs ((instance openapi-parser/schema/3.0.1:<tag>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::external-docs)
      (slot-value instance 'openapi-parser/schema/3.0.1::external-docs)
      default))

(defmethod ->$ref ((instance openapi-parser/schema/3.0.1:<reference>) &optional default)
  (if (slot-boundp instance '$ref)
      (slot-value instance '$ref)
      default))

(defmethod ->nullable ((instance openapi-parser/schema/3.0.1:<schema>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::nullable)
      (slot-value instance 'openapi-parser/schema/3.0.1::nullable)
      default))

(defmethod ->discriminator ((instance openapi-parser/schema/3.0.1:<schema>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::discriminator)
      (slot-value instance 'openapi-parser/schema/3.0.1::discriminator)
      default))

(defmethod ->read-only ((instance openapi-parser/schema/3.0.1:<schema>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::read-only)
      (slot-value instance 'openapi-parser/schema/3.0.1::read-only)
      default))

(defmethod ->write-only ((instance openapi-parser/schema/3.0.1:<schema>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::write-only)
      (slot-value instance 'openapi-parser/schema/3.0.1::write-only)
      default))

(defmethod ->xml ((instance openapi-parser/schema/3.0.1:<schema>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::xml)
      (slot-value instance 'openapi-parser/schema/3.0.1::xml)
      default))

(defmethod ->external-docs ((instance openapi-parser/schema/3.0.1:<schema>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::external-docs)
      (slot-value instance 'openapi-parser/schema/3.0.1::external-docs)
      default))

(defmethod ->example ((instance openapi-parser/schema/3.0.1:<schema>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::example)
      (slot-value instance 'openapi-parser/schema/3.0.1::example)
      default))

(defmethod ->deprecated ((instance openapi-parser/schema/3.0.1:<schema>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::deprecated)
      (slot-value instance 'openapi-parser/schema/3.0.1::deprecated)
      default))

(defmethod ->property-name
           ((instance openapi-parser/schema/3.0.1:<discriminator>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::property-name)
      (slot-value instance 'openapi-parser/schema/3.0.1::property-name)
      default))

(defmethod ->mapping ((instance openapi-parser/schema/3.0.1:<discriminator>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::mapping)
      (slot-value instance 'openapi-parser/schema/3.0.1::mapping)
      default))

(defmethod ->name ((instance openapi-parser/schema/3.0.1:<xml>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::name)
      (slot-value instance 'openapi-parser/schema/3.0.1::name)
      default))

(defmethod ->namespace ((instance openapi-parser/schema/3.0.1:<xml>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::namespace)
      (slot-value instance 'openapi-parser/schema/3.0.1::namespace)
      default))

(defmethod ->prefix ((instance openapi-parser/schema/3.0.1:<xml>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::prefix)
      (slot-value instance 'openapi-parser/schema/3.0.1::prefix)
      default))

(defmethod ->attribute ((instance openapi-parser/schema/3.0.1:<xml>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::attribute)
      (slot-value instance 'openapi-parser/schema/3.0.1::attribute)
      default))

(defmethod ->wrapped ((instance openapi-parser/schema/3.0.1:<xml>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::wrapped)
      (slot-value instance 'openapi-parser/schema/3.0.1::wrapped)
      default))

(defmethod ->type ((instance openapi-parser/schema/3.0.1:<security-scheme>) &optional default)
  (if (slot-boundp instance 'type)
      (slot-value instance 'type)
      default))

(defmethod ->description
           ((instance openapi-parser/schema/3.0.1:<security-scheme>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::description)
      (slot-value instance 'openapi-parser/schema/3.0.1::description)
      default))

(defmethod ->name ((instance openapi-parser/schema/3.0.1:<security-scheme>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::name)
      (slot-value instance 'openapi-parser/schema/3.0.1::name)
      default))

(defmethod ->in ((instance openapi-parser/schema/3.0.1:<security-scheme>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::in)
      (slot-value instance 'openapi-parser/schema/3.0.1::in)
      default))

(defmethod ->scheme ((instance openapi-parser/schema/3.0.1:<security-scheme>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::scheme)
      (slot-value instance 'openapi-parser/schema/3.0.1::scheme)
      default))

(defmethod ->bearer-format
           ((instance openapi-parser/schema/3.0.1:<security-scheme>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::bearer-format)
      (slot-value instance 'openapi-parser/schema/3.0.1::bearer-format)
      default))

(defmethod ->flows ((instance openapi-parser/schema/3.0.1:<security-scheme>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::flows)
      (slot-value instance 'openapi-parser/schema/3.0.1::flows)
      default))

(defmethod ->open-id-connect-url
           ((instance openapi-parser/schema/3.0.1:<security-scheme>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::open-id-connect-url)
      (slot-value instance 'openapi-parser/schema/3.0.1::open-id-connect-url)
      default))

(defmethod ->implicit ((instance openapi-parser/schema/3.0.1:<oauth-flow>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::implicit)
      (slot-value instance 'openapi-parser/schema/3.0.1::implicit)
      default))

(defmethod ->password ((instance openapi-parser/schema/3.0.1:<oauth-flow>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::password)
      (slot-value instance 'openapi-parser/schema/3.0.1::password)
      default))

(defmethod ->client-credentials
           ((instance openapi-parser/schema/3.0.1:<oauth-flow>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::client-credentials)
      (slot-value instance 'openapi-parser/schema/3.0.1::client-credentials)
      default))

(defmethod ->authorization-code
           ((instance openapi-parser/schema/3.0.1:<oauth-flow>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::authorization-code)
      (slot-value instance 'openapi-parser/schema/3.0.1::authorization-code)
      default))

(defmethod ->authorization-url
           ((instance openapi-parser/schema/3.0.1:<o-auth-flow>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::authorization-url)
      (slot-value instance 'openapi-parser/schema/3.0.1::authorization-url)
      default))

(defmethod ->token-url ((instance openapi-parser/schema/3.0.1:<o-auth-flow>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::token-url)
      (slot-value instance 'openapi-parser/schema/3.0.1::token-url)
      default))

(defmethod ->refresh-url ((instance openapi-parser/schema/3.0.1:<o-auth-flow>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::refresh-url)
      (slot-value instance 'openapi-parser/schema/3.0.1::refresh-url)
      default))

(defmethod ->scopes ((instance openapi-parser/schema/3.0.1:<o-auth-flow>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.0.1::scopes)
      (slot-value instance 'openapi-parser/schema/3.0.1::scopes)
      default))

(defmethod ->field*
           ((instance openapi-parser/schema/3.0.1:<security-requirement>) &optional default)
  (if (slot-boundp instance 'field*)
      (slot-value instance 'field*)
      default))

(defmethod ->openapi ((instance openapi-parser/schema/3.1.0:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::openapi)
      (slot-value instance 'openapi-parser/schema/3.1.0::openapi)
      default))

(defmethod ->info ((instance openapi-parser/schema/3.1.0:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::info)
      (slot-value instance 'openapi-parser/schema/3.1.0::info)
      default))

(defmethod ->json-schema-dialect
           ((instance openapi-parser/schema/3.1.0:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::json-schema-dialect)
      (slot-value instance 'openapi-parser/schema/3.1.0::json-schema-dialect)
      default))

(defmethod ->servers ((instance openapi-parser/schema/3.1.0:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::servers)
      (slot-value instance 'openapi-parser/schema/3.1.0::servers)
      default))

(defmethod ->paths ((instance openapi-parser/schema/3.1.0:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::paths)
      (slot-value instance 'openapi-parser/schema/3.1.0::paths)
      default))

(defmethod ->webhooks ((instance openapi-parser/schema/3.1.0:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::webhooks)
      (slot-value instance 'openapi-parser/schema/3.1.0::webhooks)
      default))

(defmethod ->components ((instance openapi-parser/schema/3.1.0:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::components)
      (slot-value instance 'openapi-parser/schema/3.1.0::components)
      default))

(defmethod ->security ((instance openapi-parser/schema/3.1.0:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::security)
      (slot-value instance 'openapi-parser/schema/3.1.0::security)
      default))

(defmethod ->tags ((instance openapi-parser/schema/3.1.0:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::tags)
      (slot-value instance 'openapi-parser/schema/3.1.0::tags)
      default))

(defmethod ->external-docs ((instance openapi-parser/schema/3.1.0:<open-api>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::external-docs)
      (slot-value instance 'openapi-parser/schema/3.1.0::external-docs)
      default))

(defmethod ->title ((instance openapi-parser/schema/3.1.0:<info>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::title)
      (slot-value instance 'openapi-parser/schema/3.1.0::title)
      default))

(defmethod ->summary ((instance openapi-parser/schema/3.1.0:<info>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::summary)
      (slot-value instance 'openapi-parser/schema/3.1.0::summary)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.1.0:<info>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::description)
      (slot-value instance 'openapi-parser/schema/3.1.0::description)
      default))

(defmethod ->terms-of-service ((instance openapi-parser/schema/3.1.0:<info>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::terms-of-service)
      (slot-value instance 'openapi-parser/schema/3.1.0::terms-of-service)
      default))

(defmethod ->contact ((instance openapi-parser/schema/3.1.0:<info>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::contact)
      (slot-value instance 'openapi-parser/schema/3.1.0::contact)
      default))

(defmethod ->license ((instance openapi-parser/schema/3.1.0:<info>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::license)
      (slot-value instance 'openapi-parser/schema/3.1.0::license)
      default))

(defmethod ->version ((instance openapi-parser/schema/3.1.0:<info>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::version)
      (slot-value instance 'openapi-parser/schema/3.1.0::version)
      default))

(defmethod ->name ((instance openapi-parser/schema/3.1.0:<contact>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::name)
      (slot-value instance 'openapi-parser/schema/3.1.0::name)
      default))

(defmethod ->url ((instance openapi-parser/schema/3.1.0:<contact>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::url)
      (slot-value instance 'openapi-parser/schema/3.1.0::url)
      default))

(defmethod ->email ((instance openapi-parser/schema/3.1.0:<contact>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::email)
      (slot-value instance 'openapi-parser/schema/3.1.0::email)
      default))

(defmethod ->name ((instance openapi-parser/schema/3.1.0:<license>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::name)
      (slot-value instance 'openapi-parser/schema/3.1.0::name)
      default))

(defmethod ->identifier ((instance openapi-parser/schema/3.1.0:<license>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::identifier)
      (slot-value instance 'openapi-parser/schema/3.1.0::identifier)
      default))

(defmethod ->url ((instance openapi-parser/schema/3.1.0:<license>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::url)
      (slot-value instance 'openapi-parser/schema/3.1.0::url)
      default))

(defmethod ->url ((instance openapi-parser/schema/3.1.0:<server>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::url)
      (slot-value instance 'openapi-parser/schema/3.1.0::url)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.1.0:<server>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::description)
      (slot-value instance 'openapi-parser/schema/3.1.0::description)
      default))

(defmethod ->variables ((instance openapi-parser/schema/3.1.0:<server>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::variables)
      (slot-value instance 'openapi-parser/schema/3.1.0::variables)
      default))

(defmethod ->enum ((instance openapi-parser/schema/3.1.0:<server-variable>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::enum)
      (slot-value instance 'openapi-parser/schema/3.1.0::enum)
      default))

(defmethod ->default ((instance openapi-parser/schema/3.1.0:<server-variable>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::default)
      (slot-value instance 'openapi-parser/schema/3.1.0::default)
      default))

(defmethod ->description
           ((instance openapi-parser/schema/3.1.0:<server-variable>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::description)
      (slot-value instance 'openapi-parser/schema/3.1.0::description)
      default))

(defmethod ->schemas ((instance openapi-parser/schema/3.1.0:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::schemas)
      (slot-value instance 'openapi-parser/schema/3.1.0::schemas)
      default))

(defmethod ->responses ((instance openapi-parser/schema/3.1.0:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::responses)
      (slot-value instance 'openapi-parser/schema/3.1.0::responses)
      default))

(defmethod ->parameters ((instance openapi-parser/schema/3.1.0:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::parameters)
      (slot-value instance 'openapi-parser/schema/3.1.0::parameters)
      default))

(defmethod ->examples ((instance openapi-parser/schema/3.1.0:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::examples)
      (slot-value instance 'openapi-parser/schema/3.1.0::examples)
      default))

(defmethod ->request-bodies ((instance openapi-parser/schema/3.1.0:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::request-bodies)
      (slot-value instance 'openapi-parser/schema/3.1.0::request-bodies)
      default))

(defmethod ->headers ((instance openapi-parser/schema/3.1.0:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::headers)
      (slot-value instance 'openapi-parser/schema/3.1.0::headers)
      default))

(defmethod ->security-schemes
           ((instance openapi-parser/schema/3.1.0:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::security-schemes)
      (slot-value instance 'openapi-parser/schema/3.1.0::security-schemes)
      default))

(defmethod ->links ((instance openapi-parser/schema/3.1.0:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::links)
      (slot-value instance 'openapi-parser/schema/3.1.0::links)
      default))

(defmethod ->callbacks ((instance openapi-parser/schema/3.1.0:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::callbacks)
      (slot-value instance 'openapi-parser/schema/3.1.0::callbacks)
      default))

(defmethod ->path-items ((instance openapi-parser/schema/3.1.0:<components>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::path-items)
      (slot-value instance 'openapi-parser/schema/3.1.0::path-items)
      default))

(defmethod ->field* ((instance openapi-parser/schema/3.1.0:<paths>) &optional default)
  (if (slot-boundp instance 'field*)
      (slot-value instance 'field*)
      default))

(defmethod ->$ref ((instance openapi-parser/schema/3.1.0:<path-item>) &optional default)
  (if (slot-boundp instance '$ref)
      (slot-value instance '$ref)
      default))

(defmethod ->summary ((instance openapi-parser/schema/3.1.0:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::summary)
      (slot-value instance 'openapi-parser/schema/3.1.0::summary)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.1.0:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::description)
      (slot-value instance 'openapi-parser/schema/3.1.0::description)
      default))

(defmethod ->get ((instance openapi-parser/schema/3.1.0:<path-item>) &optional default)
  (if (slot-boundp instance 'get)
      (slot-value instance 'get)
      default))

(defmethod ->put ((instance openapi-parser/schema/3.1.0:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::put)
      (slot-value instance 'openapi-parser/schema/3.1.0::put)
      default))

(defmethod ->post ((instance openapi-parser/schema/3.1.0:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::post)
      (slot-value instance 'openapi-parser/schema/3.1.0::post)
      default))

(defmethod ->delete ((instance openapi-parser/schema/3.1.0:<path-item>) &optional default)
  (if (slot-boundp instance 'delete)
      (slot-value instance 'delete)
      default))

(defmethod ->options ((instance openapi-parser/schema/3.1.0:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::options)
      (slot-value instance 'openapi-parser/schema/3.1.0::options)
      default))

(defmethod ->head ((instance openapi-parser/schema/3.1.0:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::head)
      (slot-value instance 'openapi-parser/schema/3.1.0::head)
      default))

(defmethod ->patch ((instance openapi-parser/schema/3.1.0:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::patch)
      (slot-value instance 'openapi-parser/schema/3.1.0::patch)
      default))

(defmethod ->trace ((instance openapi-parser/schema/3.1.0:<path-item>) &optional default)
  (if (slot-boundp instance 'trace)
      (slot-value instance 'trace)
      default))

(defmethod ->servers ((instance openapi-parser/schema/3.1.0:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::servers)
      (slot-value instance 'openapi-parser/schema/3.1.0::servers)
      default))

(defmethod ->parameters ((instance openapi-parser/schema/3.1.0:<path-item>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::parameters)
      (slot-value instance 'openapi-parser/schema/3.1.0::parameters)
      default))

(defmethod ->tags ((instance openapi-parser/schema/3.1.0:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::tags)
      (slot-value instance 'openapi-parser/schema/3.1.0::tags)
      default))

(defmethod ->summary ((instance openapi-parser/schema/3.1.0:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::summary)
      (slot-value instance 'openapi-parser/schema/3.1.0::summary)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.1.0:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::description)
      (slot-value instance 'openapi-parser/schema/3.1.0::description)
      default))

(defmethod ->external-docs ((instance openapi-parser/schema/3.1.0:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::external-docs)
      (slot-value instance 'openapi-parser/schema/3.1.0::external-docs)
      default))

(defmethod ->operation-id ((instance openapi-parser/schema/3.1.0:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::operation-id)
      (slot-value instance 'openapi-parser/schema/3.1.0::operation-id)
      default))

(defmethod ->parameters ((instance openapi-parser/schema/3.1.0:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::parameters)
      (slot-value instance 'openapi-parser/schema/3.1.0::parameters)
      default))

(defmethod ->request-body ((instance openapi-parser/schema/3.1.0:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::request-body)
      (slot-value instance 'openapi-parser/schema/3.1.0::request-body)
      default))

(defmethod ->responses ((instance openapi-parser/schema/3.1.0:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::responses)
      (slot-value instance 'openapi-parser/schema/3.1.0::responses)
      default))

(defmethod ->callbacks ((instance openapi-parser/schema/3.1.0:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::callbacks)
      (slot-value instance 'openapi-parser/schema/3.1.0::callbacks)
      default))

(defmethod ->deprecated ((instance openapi-parser/schema/3.1.0:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::deprecated)
      (slot-value instance 'openapi-parser/schema/3.1.0::deprecated)
      default))

(defmethod ->security ((instance openapi-parser/schema/3.1.0:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::security)
      (slot-value instance 'openapi-parser/schema/3.1.0::security)
      default))

(defmethod ->servers ((instance openapi-parser/schema/3.1.0:<operation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::servers)
      (slot-value instance 'openapi-parser/schema/3.1.0::servers)
      default))

(defmethod ->description
           ((instance openapi-parser/schema/3.1.0:<external-documentation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::description)
      (slot-value instance 'openapi-parser/schema/3.1.0::description)
      default))

(defmethod ->url
           ((instance openapi-parser/schema/3.1.0:<external-documentation>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::url)
      (slot-value instance 'openapi-parser/schema/3.1.0::url)
      default))

(defmethod ->name ((instance openapi-parser/schema/3.1.0:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::name)
      (slot-value instance 'openapi-parser/schema/3.1.0::name)
      default))

(defmethod ->in ((instance openapi-parser/schema/3.1.0:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::in)
      (slot-value instance 'openapi-parser/schema/3.1.0::in)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.1.0:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::description)
      (slot-value instance 'openapi-parser/schema/3.1.0::description)
      default))

(defmethod ->required ((instance openapi-parser/schema/3.1.0:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::required)
      (slot-value instance 'openapi-parser/schema/3.1.0::required)
      default))

(defmethod ->deprecated ((instance openapi-parser/schema/3.1.0:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::deprecated)
      (slot-value instance 'openapi-parser/schema/3.1.0::deprecated)
      default))

(defmethod ->allow-empty-value
           ((instance openapi-parser/schema/3.1.0:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::allow-empty-value)
      (slot-value instance 'openapi-parser/schema/3.1.0::allow-empty-value)
      default))

(defmethod ->style ((instance openapi-parser/schema/3.1.0:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::style)
      (slot-value instance 'openapi-parser/schema/3.1.0::style)
      default))

(defmethod ->explode ((instance openapi-parser/schema/3.1.0:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::explode)
      (slot-value instance 'openapi-parser/schema/3.1.0::explode)
      default))

(defmethod ->allow-reserved ((instance openapi-parser/schema/3.1.0:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::allow-reserved)
      (slot-value instance 'openapi-parser/schema/3.1.0::allow-reserved)
      default))

(defmethod ->schema ((instance openapi-parser/schema/3.1.0:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::schema)
      (slot-value instance 'openapi-parser/schema/3.1.0::schema)
      default))

(defmethod ->example ((instance openapi-parser/schema/3.1.0:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::example)
      (slot-value instance 'openapi-parser/schema/3.1.0::example)
      default))

(defmethod ->examples ((instance openapi-parser/schema/3.1.0:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::examples)
      (slot-value instance 'openapi-parser/schema/3.1.0::examples)
      default))

(defmethod ->content ((instance openapi-parser/schema/3.1.0:<parameter>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::content)
      (slot-value instance 'openapi-parser/schema/3.1.0::content)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.1.0:<request-body>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::description)
      (slot-value instance 'openapi-parser/schema/3.1.0::description)
      default))

(defmethod ->content ((instance openapi-parser/schema/3.1.0:<request-body>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::content)
      (slot-value instance 'openapi-parser/schema/3.1.0::content)
      default))

(defmethod ->required ((instance openapi-parser/schema/3.1.0:<request-body>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::required)
      (slot-value instance 'openapi-parser/schema/3.1.0::required)
      default))

(defmethod ->schema ((instance openapi-parser/schema/3.1.0:<media-type>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::schema)
      (slot-value instance 'openapi-parser/schema/3.1.0::schema)
      default))

(defmethod ->example ((instance openapi-parser/schema/3.1.0:<media-type>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::example)
      (slot-value instance 'openapi-parser/schema/3.1.0::example)
      default))

(defmethod ->examples ((instance openapi-parser/schema/3.1.0:<media-type>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::examples)
      (slot-value instance 'openapi-parser/schema/3.1.0::examples)
      default))

(defmethod ->encoding ((instance openapi-parser/schema/3.1.0:<media-type>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::encoding)
      (slot-value instance 'openapi-parser/schema/3.1.0::encoding)
      default))

(defmethod ->content-type ((instance openapi-parser/schema/3.1.0:<encoding>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::content-type)
      (slot-value instance 'openapi-parser/schema/3.1.0::content-type)
      default))

(defmethod ->headers ((instance openapi-parser/schema/3.1.0:<encoding>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::headers)
      (slot-value instance 'openapi-parser/schema/3.1.0::headers)
      default))

(defmethod ->style ((instance openapi-parser/schema/3.1.0:<encoding>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::style)
      (slot-value instance 'openapi-parser/schema/3.1.0::style)
      default))

(defmethod ->explode ((instance openapi-parser/schema/3.1.0:<encoding>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::explode)
      (slot-value instance 'openapi-parser/schema/3.1.0::explode)
      default))

(defmethod ->allow-reserved ((instance openapi-parser/schema/3.1.0:<encoding>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::allow-reserved)
      (slot-value instance 'openapi-parser/schema/3.1.0::allow-reserved)
      default))

(defmethod ->field* ((instance openapi-parser/schema/3.1.0:<responses>) &optional default)
  (if (slot-boundp instance 'field*)
      (slot-value instance 'field*)
      default))

(defmethod ->default ((instance openapi-parser/schema/3.1.0:<responses>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::default)
      (slot-value instance 'openapi-parser/schema/3.1.0::default)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.1.0:<response>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::description)
      (slot-value instance 'openapi-parser/schema/3.1.0::description)
      default))

(defmethod ->headers ((instance openapi-parser/schema/3.1.0:<response>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::headers)
      (slot-value instance 'openapi-parser/schema/3.1.0::headers)
      default))

(defmethod ->content ((instance openapi-parser/schema/3.1.0:<response>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::content)
      (slot-value instance 'openapi-parser/schema/3.1.0::content)
      default))

(defmethod ->links ((instance openapi-parser/schema/3.1.0:<response>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::links)
      (slot-value instance 'openapi-parser/schema/3.1.0::links)
      default))

(defmethod ->field* ((instance openapi-parser/schema/3.1.0:<callback>) &optional default)
  (if (slot-boundp instance 'field*)
      (slot-value instance 'field*)
      default))

(defmethod ->summary ((instance openapi-parser/schema/3.1.0:<example>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::summary)
      (slot-value instance 'openapi-parser/schema/3.1.0::summary)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.1.0:<example>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::description)
      (slot-value instance 'openapi-parser/schema/3.1.0::description)
      default))

(defmethod ->value ((instance openapi-parser/schema/3.1.0:<example>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::value)
      (slot-value instance 'openapi-parser/schema/3.1.0::value)
      default))

(defmethod ->external-value ((instance openapi-parser/schema/3.1.0:<example>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::external-value)
      (slot-value instance 'openapi-parser/schema/3.1.0::external-value)
      default))

(defmethod ->operation-ref ((instance openapi-parser/schema/3.1.0:<link>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::operation-ref)
      (slot-value instance 'openapi-parser/schema/3.1.0::operation-ref)
      default))

(defmethod ->operation-id ((instance openapi-parser/schema/3.1.0:<link>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::operation-id)
      (slot-value instance 'openapi-parser/schema/3.1.0::operation-id)
      default))

(defmethod ->parameters ((instance openapi-parser/schema/3.1.0:<link>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::parameters)
      (slot-value instance 'openapi-parser/schema/3.1.0::parameters)
      default))

(defmethod ->request-body ((instance openapi-parser/schema/3.1.0:<link>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::request-body)
      (slot-value instance 'openapi-parser/schema/3.1.0::request-body)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.1.0:<link>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::description)
      (slot-value instance 'openapi-parser/schema/3.1.0::description)
      default))

(defmethod ->server ((instance openapi-parser/schema/3.1.0:<link>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::server)
      (slot-value instance 'openapi-parser/schema/3.1.0::server)
      default))

(defmethod ->name ((instance openapi-parser/schema/3.1.0:<tag>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::name)
      (slot-value instance 'openapi-parser/schema/3.1.0::name)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.1.0:<tag>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::description)
      (slot-value instance 'openapi-parser/schema/3.1.0::description)
      default))

(defmethod ->external-docs ((instance openapi-parser/schema/3.1.0:<tag>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::external-docs)
      (slot-value instance 'openapi-parser/schema/3.1.0::external-docs)
      default))

(defmethod ->$ref ((instance openapi-parser/schema/3.1.0:<reference>) &optional default)
  (if (slot-boundp instance '$ref)
      (slot-value instance '$ref)
      default))

(defmethod ->summary ((instance openapi-parser/schema/3.1.0:<reference>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::summary)
      (slot-value instance 'openapi-parser/schema/3.1.0::summary)
      default))

(defmethod ->description ((instance openapi-parser/schema/3.1.0:<reference>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::description)
      (slot-value instance 'openapi-parser/schema/3.1.0::description)
      default))

(defmethod ->discriminator ((instance openapi-parser/schema/3.1.0:<schema>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::discriminator)
      (slot-value instance 'openapi-parser/schema/3.1.0::discriminator)
      default))

(defmethod ->xml ((instance openapi-parser/schema/3.1.0:<schema>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::xml)
      (slot-value instance 'openapi-parser/schema/3.1.0::xml)
      default))

(defmethod ->external-docs ((instance openapi-parser/schema/3.1.0:<schema>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::external-docs)
      (slot-value instance 'openapi-parser/schema/3.1.0::external-docs)
      default))

(defmethod ->example ((instance openapi-parser/schema/3.1.0:<schema>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::example)
      (slot-value instance 'openapi-parser/schema/3.1.0::example)
      default))

(defmethod ->property-name
           ((instance openapi-parser/schema/3.1.0:<discriminator>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::property-name)
      (slot-value instance 'openapi-parser/schema/3.1.0::property-name)
      default))

(defmethod ->mapping ((instance openapi-parser/schema/3.1.0:<discriminator>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::mapping)
      (slot-value instance 'openapi-parser/schema/3.1.0::mapping)
      default))

(defmethod ->name ((instance openapi-parser/schema/3.1.0:<xml>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::name)
      (slot-value instance 'openapi-parser/schema/3.1.0::name)
      default))

(defmethod ->namespace ((instance openapi-parser/schema/3.1.0:<xml>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::namespace)
      (slot-value instance 'openapi-parser/schema/3.1.0::namespace)
      default))

(defmethod ->prefix ((instance openapi-parser/schema/3.1.0:<xml>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::prefix)
      (slot-value instance 'openapi-parser/schema/3.1.0::prefix)
      default))

(defmethod ->attribute ((instance openapi-parser/schema/3.1.0:<xml>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::attribute)
      (slot-value instance 'openapi-parser/schema/3.1.0::attribute)
      default))

(defmethod ->wrapped ((instance openapi-parser/schema/3.1.0:<xml>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::wrapped)
      (slot-value instance 'openapi-parser/schema/3.1.0::wrapped)
      default))

(defmethod ->type ((instance openapi-parser/schema/3.1.0:<security-scheme>) &optional default)
  (if (slot-boundp instance 'type)
      (slot-value instance 'type)
      default))

(defmethod ->description
           ((instance openapi-parser/schema/3.1.0:<security-scheme>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::description)
      (slot-value instance 'openapi-parser/schema/3.1.0::description)
      default))

(defmethod ->name ((instance openapi-parser/schema/3.1.0:<security-scheme>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::name)
      (slot-value instance 'openapi-parser/schema/3.1.0::name)
      default))

(defmethod ->in ((instance openapi-parser/schema/3.1.0:<security-scheme>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::in)
      (slot-value instance 'openapi-parser/schema/3.1.0::in)
      default))

(defmethod ->scheme ((instance openapi-parser/schema/3.1.0:<security-scheme>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::scheme)
      (slot-value instance 'openapi-parser/schema/3.1.0::scheme)
      default))

(defmethod ->bearer-format
           ((instance openapi-parser/schema/3.1.0:<security-scheme>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::bearer-format)
      (slot-value instance 'openapi-parser/schema/3.1.0::bearer-format)
      default))

(defmethod ->flows ((instance openapi-parser/schema/3.1.0:<security-scheme>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::flows)
      (slot-value instance 'openapi-parser/schema/3.1.0::flows)
      default))

(defmethod ->open-id-connect-url
           ((instance openapi-parser/schema/3.1.0:<security-scheme>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::open-id-connect-url)
      (slot-value instance 'openapi-parser/schema/3.1.0::open-id-connect-url)
      default))

(defmethod ->implicit ((instance openapi-parser/schema/3.1.0:<oauth-flow>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::implicit)
      (slot-value instance 'openapi-parser/schema/3.1.0::implicit)
      default))

(defmethod ->password ((instance openapi-parser/schema/3.1.0:<oauth-flow>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::password)
      (slot-value instance 'openapi-parser/schema/3.1.0::password)
      default))

(defmethod ->client-credentials
           ((instance openapi-parser/schema/3.1.0:<oauth-flow>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::client-credentials)
      (slot-value instance 'openapi-parser/schema/3.1.0::client-credentials)
      default))

(defmethod ->authorization-code
           ((instance openapi-parser/schema/3.1.0:<oauth-flow>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::authorization-code)
      (slot-value instance 'openapi-parser/schema/3.1.0::authorization-code)
      default))

(defmethod ->authorization-url
           ((instance openapi-parser/schema/3.1.0:<o-auth-flow>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::authorization-url)
      (slot-value instance 'openapi-parser/schema/3.1.0::authorization-url)
      default))

(defmethod ->token-url ((instance openapi-parser/schema/3.1.0:<o-auth-flow>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::token-url)
      (slot-value instance 'openapi-parser/schema/3.1.0::token-url)
      default))

(defmethod ->refresh-url ((instance openapi-parser/schema/3.1.0:<o-auth-flow>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::refresh-url)
      (slot-value instance 'openapi-parser/schema/3.1.0::refresh-url)
      default))

(defmethod ->scopes ((instance openapi-parser/schema/3.1.0:<o-auth-flow>) &optional default)
  (if (slot-boundp instance 'openapi-parser/schema/3.1.0::scopes)
      (slot-value instance 'openapi-parser/schema/3.1.0::scopes)
      default))

(defmethod ->field*
           ((instance openapi-parser/schema/3.1.0:<security-requirement>) &optional default)
  (if (slot-boundp instance 'field*)
      (slot-value instance 'field*)
      default))