(in-package :openapi-parser/schema/3/interface)

(defclass <json-schema> () ())

(defclass <open-api> () ())
(defclass <info> () ())
(defclass <contact> () ())
(defclass <license> () ())
(defclass <server> () ())
(defclass <server-variable> () ())
(defclass <components> () ())
(defclass <paths> () ())
(defclass <path-item> () ())
(defclass <operation> () ())
(defclass <external-documentation> () ())
(defclass <parameter> () ())
(defclass <request-body> () ())
(defclass <media-type> () ())
(defclass <encoding> () ())
(defclass <responses> () ())
(defclass <response> () ())
(defclass <callback> () ())
(defclass <example> () ())
(defclass <link> () ())
(defclass <header> () ())
(defclass <tag> () ())
(defclass <reference> () ())
(defclass <schema> () ())
(defclass <discriminator> () ())
(defclass <xml> () ())
(defclass <security-scheme> () ())
(defclass <oauth-flow> () ())
(defclass <o-auth-flow> () ())
(defclass <security-requirement> () ())
